#List of dbs availble in couch db̥
G̥ET http://admin:password@localhost:5984/_all_dbs̥ HTTP/1.1̥
content-type: application/json


PUT http://admin:password@localhost:5984/test/_design/lotus/_update/updateCategory/test HTTP/1.1̥̥
content-type: application/json

{
 "categories": ["test1","test2","test3","test1","test2","test3","test1","test2","test3","test1","test2","test3"]
}